### PR TITLE
Fix `componentLoaderProvider` link.

### PR DESCRIPTION
**Pull request by lig**

### CODE REVIEW

**Comment by metamatt** [comment]
@btford: Why sit on patches to the getting-started docs for weeks? The [current example there](http://angular.github.io/router/getting-started) is pretty badly out of date and broken, both with respect to the angular/router code itself having changed out from under it (example, `ng-viewport` replacing `router-view-port`) and internal inconsistencies (`app` vs `myApp`, `components/detail` vs `components/home`). I'd send a PR to fix the example, but if you're not merging things like this one, I'd have small hope of that being merged.

**Comment by btford** [comment]
> Why sit on patches to the getting-started docs for weeks?

There are only twenty four hours in a day, there's a lot of activity on this repo, and I'm an imperfect fallible human being just like everyone else.

**Comment by metamatt** [comment]
Fair enough, I don't mean to be mean, I just wonder if it's worth sending you doc patches. I'd be happy to save you some time if I could. And I don't mean to hijack this PR either.

**Comment by btford** [comment]
> I just wonder if it's worth sending you doc patches.

Yep! Definitely send 'em. I may not get around to merging them immediately, but I do value docs contributions and hope to spend more time reviewing/merging them this week.

**Comment by metamatt** [comment]
Cool, will do. Um, I have a question about how to do this change. Is there a better place for this discussion than in this PR? Happy to take the discussion to a better place, for lack of that, I'll ask here.

Question: looking at https://github.com/angular/router/tree/gh-pages, all the commit titles are "gen docs", so I presume you're generating the gh-pages content from https://github.com/angular/router/tree/master/docs/content, and it's better to patch the source (e.g. https://github.com/angular/router/blob/master/docs/content/getting-started.md) than the generated output (e.g. what the present PR does)?

Also, trying to generate the generated docs, `gulp dgeni` fails with an unhandled EPIPE after `info:    running processor: renderMarkdownProcessor`. I assume this means some of my tooling dependencies are broken. I just did `npm install` and `./node_modules/.bin/gulp dgeni`. The copy of `marked` installed by npm seems to work; `./node_modules/.bin/marked docs/content/getting-started.md` produces reasonable output.

Hmm, maybe it's timing related. I ran `gulp dgeni` a bunch of times and eventually it worked. But it still mostly fails.

**Comment by metamatt** [comment]
Well. And many of the problems in the generated page (which is live at http://angular.github.io/router/getting-started) are already fixed in the source. The source is at 0.5.0, the gh-pages branch last regenerated at 0.3.0. In fact, the source docs/content/getting-started.md has already fixed the problem in this PR #150.

May I suggest you regenerate the docs and push gh-pages.

**Comment by PascalPrecht** [comment]
@metamatt Yes, the docs are generated using the Dgeni docs generator. And you're also right with making the change to the actual source rather than the generated output, since it gets overwritten written with the next cycle. Also correct, this is already fixed in the source. Therefore I'll close this issue. Thank you for you patience though!

@lig Thank you for your contribution !

**Pull request closed without merging**
