### PR TITLE
chore(package.json): adds main entry to support CommonJS module loading

### PR DESCRIPTION
**Pull request by mchlbrnd**

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Thanks @mchlbrnd !

We also have a `router-es5.js` version in the dist files. Is there a way to define more than just one `main` file?

**Comment by btford** [comment]
For right now, I wouldn't worry too much about importing just the
transpiled es5 Router class.

**Comment by mchlbrnd** [comment]
Agreed! 

Cheers!

**Comment by PascalPrecht** [comment]
@mchlbrnd can you squash your commits? :)

**Comment by PascalPrecht** [comment]
Thanks @mchlbrnd !

**Comment by krasevych** [comment]
Please, Can you add "main" into ".bower.json" ?

**Pull request closed without merging**
