### PR TITLE
(REFACTOR) Renaming "view port" (and variations) to compound "viewport" equivalent

### PR DESCRIPTION
**Pull request by davidkpiano**
Here's the squashed PR, @PascalPrecht

### CODE REVIEW

**Comment by btford** [comment]
No need to create a new PR – next time just force push to the remote branch.

**Comment by PascalPrecht** [comment]
@btford are you up for that change in general? Would like to see this landing.

**Comment by btford** [comment]
Yep. Feel free to rebase + merge this, provided the tests pass.

**Comment by PascalPrecht** [comment]
Will do!

**Comment by PascalPrecht** [comment]
@davidkpiano working on fixing the e2e tests in your branch now

**Comment by btford** [comment]
@PascalPrecht – what's your status on this? I'm hoping to get it in today, so I can take over if you haven't had a chance to make headway on it yet.

**Comment by PascalPrecht** [comment]
Oh in that case, take it over. I was localizing the bug and had some work
to do then. So there aren't any wasted cycles since I haven't really
started changing code.

**Comment by btford** [comment]
Landed as fd808d5b2c0a8f2b8f9d7bbd0dbf85163c542762.

Note that I also renamed `routerViewport` to `ngViewport` and `routerLink` to `ngLink` to make things a bit more idiomatic.

**Pull request closed without merging**
