### PR TITLE
fix(getting-started): componentLoader link

### PR DESCRIPTION
**Pull request by olegskl**

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Hey @olegskl could you update your commit message to use `docs()` instead of `fix()` please? :)

**Comment by olegskl** [comment]
I'm not exactly sure why this is `docs` instead of `fix` :sleeping:

**Comment by PascalPrecht** [comment]
@olegskl You're making a change in the documentation instead of fixing a bug in the router source code.

Of course, at some point this is also a fix, since the docs otherwise would be broken but as `fix()` it'll show up in the auto generated changelog under "Bugfixes" of the "getting-started" component.

**Comment by olegskl** [comment]
I don't agree, but it's counterproductive arguing about a single dollar character.

**Comment by PascalPrecht** [comment]
Oh you don't have to close this PR. You can simply update your commit message and force push to your remote branch accordingly.

**Pull request closed without merging**
